"""Markdown analysis report."""

from analyzer.owners import OWNER_DISPLAY_NAMES
from analyzer.report.common import (
    _UPDATE_RULE_SHORT,
    _counts_as_unprocessed,
    _find_all_done_active_tasks,
    _markdown_item_line,
    _report_timestamp,
)


def generate_markdown_report(analysis, parent_issue='KAT-11542', *, label='Q3'):
    """
    生成 Markdown 格式的分析报告

    Args:
        analysis: analyze_issues() 返回的分析结果

    Returns:
        str: Markdown 文档字符串
    """
    now = _report_timestamp()
    md = f"""# Jira {label} 任务分析报告

**数据更新到**: {now}（UTC+8）{_UPDATE_RULE_SHORT}
**父任务**: {parent_issue}

## 统计概览

| 指标 | 数量 |
|------|------|
| **总条目数** | {analysis['total']} |
| **已处理** | {analysis['processed']}（{analysis.get('processed_jira', 0)} 个子任务） |
| **未处理** | {analysis['unprocessed']}（{analysis.get('unprocessed_jira', 0)} 个子任务） |
| **已排期** | {analysis.get('scheduled_unprocessed', 0)} |
| **排期已处理** | {analysis.get('scheduled_processed', 0)} |

---

"""

    # 提醒：所有条目已完成但 Jira 状态仍是活跃的子任务
    stale_tasks = _find_all_done_active_tasks(analysis)
    if stale_tasks:
        md += "## ⚠️ 请更新 Jira 状态\n\n"
        md += "以下子任务的所有条目都已处理，但 Jira 状态仍为活跃，请及时更新：\n\n"
        for t in stale_tasks:
            md += f"- **{t['key']}** {t['summary']} — 状态: {t['status']}，{t['total']} 条已完成\n"
        md += "\n---\n\n"

    md += """## 未处理项目

"""

    if analysis['grouped']:
        for task_key in sorted(analysis['grouped'].keys(), reverse=True):
            task = analysis['grouped'][task_key]
            unprocessed_items = [
                item for item in task['items']
                if _counts_as_unprocessed(item, analysis)
            ]
            if not unprocessed_items:
                continue
            md += f"### [{task_key}] {task['summary']}\n\n"
            for item in unprocessed_items:
                md += _markdown_item_line(item)
            md += "\n"

        md += "## 排期已处理\n\n"
        has_scheduled_processed = False
        for task_key in sorted(analysis['grouped'].keys(), reverse=True):
            task = analysis['grouped'][task_key]
            done_scheduled = [
                i for i in task['items']
                if i.get('is_processed') and i.get('is_scheduled')
            ]
            if not done_scheduled:
                continue
            has_scheduled_processed = True
            md += f"### [{task_key}] {task['summary']}\n\n"
            for item in done_scheduled:
                md += _markdown_item_line(item, include_status=True)
            md += "\n"
        if not has_scheduled_processed:
            md += "（无）\n\n"
    else:
        md += "🎉 太棒了！没有未处理的项目。\n"

    md += """---

*Generated by Jira Analyzer*"""

    return md
